title: Test blog
description: A blog powered by Jekyll & Chirpy
url: "https://username.github.io"  
baseurl: "" 

remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-feed
  - jekyll-seo-tag
